apiVersion: v1
kind: Service
metadata:
  name: svc-metrics-controller
spec:
  selector:
    app: metrics-controller
  ports:
    - protocol: TCP
      port: 27111
      targetPort: 27111
      nodePort: 32111
  type: NodePort