services:  
  #shard1
  shard1:    
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-sa2
    volumes:
      - shard1-data:/data/db
    restart: always
    ports:
      - "27021:27021"
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1", 
        "--bind_ip_all",
        "--port",
        "27021"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
 

networks:
  app-network:
    driver: host
  
volumes:
  shard1-data: