apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-db1-data
spec:
  replicas: 1  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: db1-data
  template:
    metadata:
      labels:
        app: db1-data
    spec:
      containers:
      - name: db1-data
        image: botcser/db1-shard1
        ports:
        - name: mongodb
          containerPort: 27020