apiVersion: v1
kind: Service
metadata:
  name: svc-device-controller
spec:
  selector:
    app: device-controller
  ports:
    - protocol: TCP
      port: 27222
      targetPort: 27222
      nodePort: 32222
  type: NodePort